define(['views/createDLA/teachersEvaluation'],
function(View) {

var formModel =  {
    response: {
        'operation-status': 'SUCCESS',
        'source-site-list': [
            'ABPI',
            'Library of Congress',
            'AMSCO',
            'Aplus',
            'Arcademic',
            'BBC',
            'Bill Nye',
            'Blue Ribbon Readers',
            'Books Should Be Free',
            'CK-12',
            'Brightstorm',
            'McDougell Littell',
            'Discovery',
            'earobics',
            'e-learning for Kids',
            'TEDEd',
            'Houghton Mifflin',
            'Exploratorium',
            'FOSS',
            'Fuel the Brain',
            'FunBrain',
            'Glencoe',
            'Houghton Mifflin Harcourt',
            'Harcourt',
            'PBS',
            'ICT Games',
            'IXL',
            'iCivics',
            'Khan',
            'AAAS',
            'Learn Alberta',
            'British Council',
            'Annenberg',
            'LearnZillion',
            'Read.gov',
            'Mahalo',
            'MangaHigh',
            'Math is Fun',
            'Math Snacks',
            'Math-Play',
            'Math Playground',
            'MightyBook',
            'Mr. Nussbaum',
            'NCTM',
            'Nat Geo',
            'NLVM',
            'NMNH',
            'NOAA',
            'NSF',
            'Nick Jr',
            'Noble Prize',
            'Oswego',
            'Pearson',
            'PhET',
            'Quizlet',
            'RIF',
            'ReadWriteThink',
            'Roy the Zebra',
            'Scholastic',
            'Sesame Street',
            'Sheppard Software',
            'Shodor',
            'Starfall',
            'Jason Project',
            'NARA',
            'Time for Kids',
            'Toon University',
            'Toy Theater',
            'TV411 or EDC?',
            'EPA',
            'WikiSaber',
            'Science Alberta',
            'Xp',
            'NASA',
            'Fun English Games',
            'DPL',
            'Compass Learning',
            'Smart Tutor',
            'National Museums of Scotland',
            'UN'
        ],
        'num-results': 0
    }
}


return formModel;

});


